const types = {
  SUBMIT_SUBSCRIBER: 'SUBMIT_SUBSCRIBER',
  CHANGE_QUALITIES: 'CHANGE_QUALITIES',
  INPUT_CHANGED: 'INPUT_CHANGED',
  INPUT_QUALITIES_CHANGED: 'INPUT_QUALITIES_CHANGED',
};

export default types;
